-- Crear schema (si no existe)
CREATE SCHEMA IF NOT EXISTS scrum;

-- =========================================================
-- Limpieza (permite re-ejecutar)
-- =========================================================
DROP TABLE IF EXISTS scrum.tareas_etiquetas CASCADE;
DROP TABLE IF EXISTS scrum.tareas CASCADE;
DROP TABLE IF EXISTS scrum.etiquetas CASCADE;
DROP TABLE IF EXISTS scrum.programadores CASCADE;
DROP TABLE IF EXISTS scrum.sprints CASCADE;
DROP TABLE IF EXISTS scrum.rol CASCADE;
DROP TABLE IF EXISTS scrum.prioridad CASCADE;
DROP TABLE IF EXISTS scrum.estado CASCADE;

DROP SEQUENCE IF EXISTS scrum.seq_sprints;
DROP SEQUENCE IF EXISTS scrum.seq_programadores;
DROP SEQUENCE IF EXISTS scrum.seq_tareas;
DROP SEQUENCE IF EXISTS scrum.seq_etiquetas;
DROP SEQUENCE IF EXISTS scrum.seq_etiquetas_tareas;

-- =========================================================
-- Secuencias
-- =========================================================
CREATE SEQUENCE scrum.seq_sprints START 1 INCREMENT 1;
CREATE SEQUENCE scrum.seq_programadores START 1 INCREMENT 1;
CREATE SEQUENCE scrum.seq_tareas START 1 INCREMENT 1;
CREATE SEQUENCE scrum.seq_etiquetas START 1 INCREMENT 1;
CREATE SEQUENCE scrum.seq_etiquetas_tareas START 1 INCREMENT 1;

-- =========================================================
-- Catálogos
-- =========================================================
CREATE TABLE scrum.rol (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE scrum.prioridad (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE scrum.estado (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL UNIQUE
);

-- =========================================================
-- Sprints
-- =========================================================
CREATE TABLE scrum.sprints (
  id BIGINT NOT NULL DEFAULT nextval('scrum.seq_sprints') PRIMARY KEY,
  nombre        VARCHAR(100) NOT NULL,
  objetivo      TEXT,
  fecha_inicio  DATE NOT NULL,
  fecha_fin     DATE NOT NULL,
  estado_sprint VARCHAR(10) NOT NULL DEFAULT 'PLANNED'
    CHECK (estado_sprint IN ('PLANNED','ACTIVE','CLOSED')),
  CONSTRAINT chk_sprint_fechas CHECK (fecha_fin >= fecha_inicio),
  CONSTRAINT uq_sprints_nombre_inicio UNIQUE (nombre, fecha_inicio)
);

ALTER SEQUENCE scrum.seq_sprints OWNED BY scrum.sprints.id;

-- =========================================================
-- Programadores
-- =========================================================
CREATE TABLE scrum.programadores (
  id BIGINT NOT NULL DEFAULT nextval('scrum.seq_programadores') PRIMARY KEY,
  nombre           VARCHAR(100) NOT NULL,
  email            VARCHAR(120) NOT NULL,
  rol_id           SMALLINT NOT NULL REFERENCES scrum.rol(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  capacidad_horas  INTEGER NOT NULL DEFAULT 0 CHECK (capacidad_horas >= 0),
  CONSTRAINT uq_programadores_nombre_email UNIQUE (nombre, email)
);

ALTER SEQUENCE scrum.seq_programadores OWNED BY scrum.programadores.id;

-- =========================================================
-- Tareas
-- =========================================================
CREATE TABLE scrum.tareas (
  id                BIGINT NOT NULL DEFAULT nextval('scrum.seq_tareas') PRIMARY KEY,
  titulo            VARCHAR(150) NOT NULL,
  descripcion       TEXT,
  story_points      INTEGER NOT NULL DEFAULT 0 CHECK (story_points BETWEEN 0 AND 100),
  prioridad_id      SMALLINT NOT NULL REFERENCES scrum.prioridad(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  estado_id         SMALLINT NOT NULL REFERENCES scrum.estado(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  estimacion_horas  NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (estimacion_horas >= 0),
  horas_invertidas  NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (horas_invertidas >= 0),
  sprint_id         BIGINT NOT NULL REFERENCES scrum.sprints(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  programador_id    BIGINT NOT NULL REFERENCES scrum.programadores(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT uq_tareas_sprint_titulo UNIQUE (sprint_id, titulo)
);

ALTER SEQUENCE scrum.seq_tareas OWNED BY scrum.tareas.id;

-- =========================================================
-- Etiquetas
-- =========================================================
CREATE TABLE scrum.etiquetas (
  id BIGINT NOT NULL DEFAULT nextval('scrum.seq_etiquetas') PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL UNIQUE
);

ALTER SEQUENCE scrum.seq_etiquetas OWNED BY scrum.etiquetas.id;

-- =========================================================
-- Relación tareas <-> etiquetas
-- =========================================================
CREATE TABLE scrum.tareas_etiquetas (
  id BIGINT NOT NULL DEFAULT nextval('scrum.seq_etiquetas_tareas') PRIMARY KEY,
  tarea_id    BIGINT NOT NULL REFERENCES scrum.tareas(id)    ON DELETE CASCADE,
  etiqueta_id BIGINT NOT NULL REFERENCES scrum.etiquetas(id) ON DELETE CASCADE,
  CONSTRAINT uq_tareas_etiquetas UNIQUE (tarea_id, etiqueta_id)
);

ALTER SEQUENCE scrum.seq_etiquetas_tareas OWNED BY scrum.tareas_etiquetas.id;